### PR TITLE
Xml file references

### PR DESCRIPTION
**Pull request by dmarks2**
I would like to contribute an XML file reference contributor. Several elements in Liferay specific XML files are expecting paths to directories or files. This file reference contributor will add code completion functionality to those XML elements. Additionally the elements are real "references", so that you can Ctrl-Click on the element to navigate to the file. The other way works, too, i.e. you can press Alt-F7 ("Find usages") on the file to find out in which XML element the file is referenced.

### CODE REVIEW

**Comment by gamerson** [comment]
thanks @dmarks2   hey @jtydhr88  can you do a quick review of the functionality?

**Comment by jtydhr88** [comment]
hey @dmarks2 and @gamerson as I will release the latest version 0.1.2 soon (maybe today), I'd like to review this changes and put it in the next version.

**Comment by jtydhr88** [comment]
hey @gamerson I am done with review and I think the changes are good to be merged.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-intellij-plugin/pull/33. [See changes here.](https://github.com/gamerson/liferay-intellij-plugin/compare/ae30966~2...ae30966) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
