### PR TITLE
INTELLIJ-53 Fix marks syntax error on bnd.bnd files

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by Seiphon** [comment]
Hi @dmarks2 , your version would be very helpful, thank you so much. And maybe next I will try to implement code assistance for Liferay taglibs in freemarker templates, can I also refer your code of freemarker?

**Comment by dmarks2** [comment]
@Seiphon I will send a pull request to you in the next days, so you can review it.

I can help in merging the Freemarker code assistance, too. There are no plans to do that in LSP as well? As far as I know the extensibility for the Freemarker stuff in IntelliJ is very limited, so it may be probably impossible to get it working together with LSP. Maybe we can discuss that later...

**Comment by dmarks2** [comment]
@Seiphon I've merged my own implementation now. It contains a complete reimplementation for bnd.bnd files, as the previous implementation handled bnd.bnd files as MANIFEST.MF files (which is wrong in my opinion). The merge contains additional features like code completions, reference resolutions, renaming support, formatting and so on.

If you want you can have a look at https://github.com/dmarks2/liferay-intellij-plugin/tree/INTELLIJ-53

If you tell me where I can send a pull request, too.

**Comment by gamerson** [comment]
hey @dmarks2   You can send it to @simonjhy  for initial review and testing, and then he can send it to me and I'll try to merge it this time.

**Pull request closed without merging**
