### PR TITLE
Additional OSGi Component properties

### PR DESCRIPTION
**Pull request by dmarks2**
Signed-off-by: Dominik Marks <Dominik.Marks@gmx.de>

### CODE REVIEW

**Comment by dmarks2** [comment]
I have added some more OSGI component properties for code completion.

**Comment by dmarks2** [comment]
lrbladejenkins says that the build failed. However a local "gradlew clean build" works without problems. What's up here?

**Comment by jtydhr88** [comment]
hey @dmarks2, I am out of office, I will help to check tomorrow, you can send the pr to me and I can do the local build to see what happen if you want.

**Comment by jtydhr88** [comment]
hey @dmarks2, do not worry, some net problems happened in our office, we will fix it soon

**Comment by yanan** [comment]
Sorry for any inconvenience. It should back to work now. We can use the following to do a retest if needs: 
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-intellij-plugin/pull/54. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
