### PR TITLE
Code Completion for resource bundle keys for Liferay Taglibs (#59)

### PR DESCRIPTION
**Pull request by dmarks2**
Signed-off-by: Dominik Marks <Dominik.Marks@gmx.de>

### CODE REVIEW

**Comment by dmarks2** [comment]
I would like to contribute a ReferenceContributor for resource bundle keys in Liferay Taglibs. Many attributes can refer to keys inside the language files. 

IntelliJ will suggest keys from available Language_XX.properties files for attributes like `<liferay-ui:message key="..." />`. It is possible to search for usage of those keys (Alt-F7) and to rename the keys on the fly (Shift-F6).

**Comment by jtydhr88** [comment]
hey @dmarks2, could you fix the conflict and resend your changes to me? thanks.

**Comment by dmarks2** [comment]
@jtydhr88 The conflicts have been resolved. To send the changes to you, your repository should be equal to liferay:master, right? At the moment your repository (master) is 7 commits behind liferay:master.

**Comment by jtydhr88** [comment]
updated, or I can just fetch your branch to test today.

**Comment by dmarks2** [comment]
Resend as https://github.com/jtydhr88/liferay-intellij-plugin/pull/16

**Pull request closed without merging**
